[server]
# runOnSave = true

[theme]
# Couleur primaire (boutons, liens) en bleu foncé
primaryColor="#1565c0" 

# Couleur de fond principale (arrière-plan du stApp)
backgroundColor="#f5f7fa" 

# Couleur de fond des composants (cartes, selectboxes, etc.)
secondaryBackgroundColor="#f0f2f6" 

# Couleur du texte
textColor="#303030" 

# Police utilisée
font="sans serif"
