[server]
# runOnSave = true

[theme]
# Couleur primaire (boutons, liens)
primaryColor="#1565c0" 

# Couleur de fond principale, en harmonie avec le style du CSS
backgroundColor="#f5f7fa" 

# Couleur de fond des composants (cartes, selectboxes, etc.)
secondaryBackgroundColor="#f0f2f6" 

# Couleur du texte
textColor="#303030" 

# Police utilis√©e
font="sans serif"
